version: "3.5"

services: 
    server:
        image: golang:1.14.6-alpine
        working_dir: /server/go-server
        volumes: 
            - .:/server
        ports: 
            - "5000:5000"
            - "6000:6000"
        depends_on: 
            - db
        entrypoint: go run cmd/main.go
        restart: always
    weather:
        image: golang:1.14.6-alpine
        working_dir: /server/weather
        volumes:
            - .:/server
        ports:
            - "6100:6100"
        entrypoint: go run cmd/main.go
        restart: always
    db:
        image: postgres:9.6.5-alpine
        ports: 
            - "5432:5432"
        volumes: 
            - ./go-server/initdb.sh:/docker-entrypoint-initdb.d/init.sh
        restart: always